# Generated by Django 6.0.3 on 2026-03-31 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=30)),
            ],
        ),
    ]
